# Generated by Django 2.0.4 on 2018-04-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HandledJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.TextField()),
                ('job_show_name', models.TextField(null=True)),
                ('job_class', models.IntegerField(default=-9, null=True)),
                ('job_issue', models.TextField(null=True)),
                ('job_url', models.TextField()),
                ('job_pay', models.IntegerField(default=-9, null=True)),
                ('job_workplace', models.IntegerField(default=-9, null=True)),
                ('job_min_edu', models.IntegerField(default=-9, null=True)),
                ('job_exp', models.IntegerField(default=-9, null=True)),
                ('job_dec', models.TextField(null=True)),
                ('company_name', models.TextField(null=True)),
                ('company_ind', models.TextField(null=True)),
                ('company_size', models.IntegerField(default=-9, null=True)),
                ('company_welfare', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.TextField()),
                ('job_show_name', models.TextField(null=True)),
                ('job_class', models.IntegerField(default=-9, null=True)),
                ('job_issue', models.TextField(null=True)),
                ('job_url', models.TextField(null=True)),
                ('job_pay', models.TextField(null=True)),
                ('job_workplace', models.TextField(null=True)),
                ('job_min_edu', models.TextField(null=True)),
                ('job_exp', models.TextField(null=True)),
                ('job_dec', models.TextField(null=True)),
                ('company_name', models.TextField(null=True)),
                ('company_ind', models.TextField(null=True)),
                ('company_size', models.TextField(null=True)),
                ('company_welfare', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('websites', models.CharField(max_length=200)),
                ('every_x_days', models.IntegerField(default=-1)),
                ('every_x_clock', models.IntegerField(default=-1)),
                ('finish_count', models.IntegerField(default=0)),
            ],
        ),
    ]
